tenant:
  slug: demo
  name: Demo Company
  domain: demo.com
branding:
  primary_color: '#007bff'
  secondary_color: '#6c757d'
  accent_color: '#28a745'
  logo_url: https://example.com/logo.png
  favicon_url: https://example.com/favicon.ico
  font_family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif
  widget_position: bottom-right
  widget_size: medium
  custom_css: ''
ai:
  model: gpt-4
  temperature: 0.7
  max_tokens: 500
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  system_prompt: 'You are a helpful customer support assistant for Demo Company.


    Your role is to:

    - Answer customer questions accurately and professionally

    - Provide information about our services and products

    - Help customers with common issues

    - Escalate complex issues to human agents when necessary


    Business Information:

    - Phone: +1-555-0100

    - Email: support@example.com

    - Hours: 09:00-17:00 America/New_York


    Always be polite, professional, and helpful. If you don''t know something, be
    honest and offer to connect them with a human agent.

    '
  fallback_responses:
  - I'm not sure I understand. Could you rephrase that?
  - I don't have that information right now. Would you like me to connect you with
    a human agent?
  - Let me help you with that. Can you provide more details?
business:
  phone: +1-555-0100
  email: support@example.com
  website: https://demo.com
  address: 123 Main Street, City, State 12345
  hours:
    monday: 09:00-17:00
    tuesday: 09:00-17:00
    wednesday: 09:00-17:00
    thursday: 09:00-17:00
    friday: 09:00-17:00
    saturday: 10:00-14:00
    sunday: closed
    timezone: America/New_York
  escalation:
    keywords:
    - speak to manager
    - human agent
    - talk to person
    - cancel subscription
    - refund
    - complaint
    confidence_threshold: 0.6
    message_threshold: 5
    escalation_message: I'll connect you with a human agent who can better assist
      you. Please hold for a moment.
features:
  chat: true
  email: true
  voice: false
  sms: false
  analytics: true
  knowledge_base: true
  file_upload: true
  sentiment_analysis: true
  multilingual: false
integrations:
  crm:
    type: none
    enabled: false
    config:
      api_key: ''
      endpoint: ''
  booking:
    type: none
    enabled: false
    config:
      api_key: ''
      calendar_url: ''
  payment:
    type: none
    enabled: false
    config:
      api_key: ''
      webhook_secret: ''
  email:
    type: smtp
    enabled: true
    config:
      from_address: support@example.com
      from_name: '{name}'
  webhooks:
    enabled: false
    endpoints:
      conversation_started: ''
      conversation_ended: ''
      message_received: ''
      escalation_requested: ''
rate_limiting:
  messages_per_minute: 20
  messages_per_hour: 100
  messages_per_day: 500
  concurrent_conversations: 10
analytics:
  track_conversations: true
  track_messages: true
  track_escalations: true
  track_sentiment: true
  goals:
    resolution_rate: 0.85
    avg_response_time_ms: 2000
    csat_target: 4.5
  retention:
    conversations_days: 365
    messages_days: 365
    analytics_days: 730
knowledge_base:
  auto_update: true
  similarity_threshold: 0.75
  max_results: 3
  source_attribution: true
  categories:
  - General FAQ
  - Product Information
  - Billing & Payments
  - Technical Support
  - Account Management
widget:
  greeting_message: Hi! How can I help you today?
  placeholder_text: Type your message...
  show_agent_avatar: true
  show_timestamps: true
  enable_emoji: true
  enable_markdown: true
  enable_file_upload: true
  allowed_file_types:
  - .pdf
  - .jpg
  - .png
  - .txt
  max_file_size_mb: 10
  offline_message: We're currently offline. Leave us a message and we'll get back
    to you!
  offline_form_enabled: true
  csat_enabled: true
  csat_trigger: conversation_end
  csat_question: How would you rate your experience today?
notifications:
  email_notifications: true
  escalation_emails:
  - support@example.com
  daily_summary: true
  weekly_report: true
